# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Connor Goldberg
tagline:          'Electrical Engineer'
description:      'Table of Contents'
url:              http://connorgoldberg.com

author:
  name:           'Connor Goldberg'
  url:            https://twitter.com/connorjan94

paginate:         5
paginate_path:    "blog/page:num"

# Custom vars
version:          1.1

github:
  repo:           https://github.com/connorjan/lanyon

excerpt_separator: <!--more-->