# Dependencies
markdown:         redcarpet
#highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Connor Goldberg
tagline:          'Electrical Engineer'
description:      'Table of Contents'
url:              http://connorgoldberg.com

author:
  name:           'Connor Goldberg'
  url:            https://twitter.com/connorjan94

gems:
    - jekyll-paginate
    - jekyll-sitemap

paginate:         	3
paginate_path:    	"blog/page:num"
paginate_path_var:	"/blog" #Used in the index of the blog

# Custom vars
version:          1.2

github:
  repo:           https://github.com/connorjan/lanyon

excerpt_separator: <!--more-->

exclude: [files, README.md, fabfile.*, .git]