# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Connor Goldberg
tagline:          'Electrical Engineer'
description:      'I do things with electricity.'
url:              http://connorgoldberg.com

author:
  name:           'Connor Goldberg'
  url:            https://twitter.com/connorjan94

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/connorjan/lanyon
